# Generated by Django 5.0.3 on 2024-08-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity_sold",
        ),
    ]
